### ISSUE TITLE
[BUG] Tests stuck in Provisioning state

### ISSUE THREAD

**Issue by alessiofilippin** [microsoft/azure-load-testing#56]
**Describe the bug**
After creating and start a test. The status remain stuck in Provisioning indefinitely.

**To Reproduce**

1. Go to tests part in the Azure Load Testing Resource (create in region North Europe)
2. Run a test.
3. See status.

**Expected behavior**
test should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/47082128/155559338-b4c0ad7f-b666-476a-be6f-6320790716e0.png)

**Additional context**

Tests doesn't seem to get always stuck in that state. But it's happening often in the last 2 days.

__we tried with different types of JMeters tests, but we got the same result__

Is there a way to check if the status of Azure Load testing is healthy somehow?

**Comment by Sachid26** [comment]
@alessiofilippin .. Thank you for reporting the issue. Adding @issacnitin from our team

**Comment by alessiofilippin** [comment]
JFYI: I left the tests running in "provisioning" over the night - I found all them failed this morning.

let me know if I can help somehow :) - thanks

![image](https://user-images.githubusercontent.com/47082128/155678231-82677633-d45c-4c03-ab6c-f5b0fb256b3c.png)

**Comment by alessiofilippin** [comment]
I also re-run some of them this morning.

![image](https://user-images.githubusercontent.com/47082128/155678601-dbcae631-b16e-4527-a41e-718b81bd3049.png)

They seem in executing state .. this looks like being an intermittent issue then.

**Comment by jwyza-pi** [comment]
I've seen this as well, sometimes it'll just sit in provisioning for hours then suddenly start running or fail.

**Comment by abranj1219** [comment]
@jwyza-pi  and @alessiofilippin  Do you still see these issues?

**Comment by jwyza-pi** [comment]
I'll keep an eye on it.  I haven't seen it happen today or yesterday, but definitely was happening a fair bit last week.

**Comment by jwyza-pi** [comment]
I have not seen this occur again, so from my perspective, we're good.

**Comment by alessiofilippin** [comment]
Same from my side - it stopped after a couple of days

**Comment by DanielLarsenNZ** [comment]
I had two stuck in provisioning today (East US 2)

**Comment by abranj1219** [comment]
We are looking into this and will get back soon!

**Comment by shilamontubig** [comment]
Same here but I was using Australia East region.

**Comment by abranj1219** [comment]
It has been fixed now. We'll keep this open for couple of more days to confirm the consistent behavior

**Comment by issacnitin** [comment]
Closing the issue as no new reports since March

**Comment by ejerskov** [comment]
This is still happening.

**Comment by hkarthik7** [comment]
Hiya, This issue still persists but intermittently. I had created 2 resources and tried creating the test cases, in one resource I can create the test cases successfully however not in the second resource.

**Comment by issacnitin** [comment]
> Hiya, This issue still persists but intermittently. I had created 2 resources and tried creating the test cases, in one resource I can create the test cases successfully however not in the second resource.

could you share your test run id

**Comment by hkarthik7** [comment]
Here is the test run id - `65cbeb5c-83de-4279-bd6a-b8378f77546e`

**Comment by issacnitin** [comment]
@hkarthik7 the test runs failed while configuring, out of 3 VMs you provisioned, only one was configured successfully, we saw the VM restarted in between configuring as well, we'd like to check your JMX and other input configuration to determine the root cause.. please use azure support to raise a ticket on us

**Comment by hkarthik7** [comment]
Cheers, will do, thank you.

**Comment by jdubagilisys** [comment]
Hi, currently experiencing this issue when trying to run tests using private test traffic mode (UK South)
